### Detección de spam
#### Automatización mediante machine learning para filtrar spam
- adaptabilidad
- presición 
- automatización

#### regla de bayes
- es una formula que describe como actualizar las probabilidades de hipótesis cuando dispone de nueva evidencia

- P(A|B) = P(B|A) * P(A) / P(B)
donde:
- P(A|B) es la probabilidad de A dado B
- P(B|A) es la probabilidad de B dado A
- P(A) es la probabilidad previa de A
- P(B) es la probabilidad total de B 

#### naive bayes
- es una aplicación del teorema de bayes con la asunción "naive" de que las características son independientes entre sí
- P(A|B1, B2, ..., Bn) = P(A) * P(B1|A) * P(B2|A) * ... * P(Bn|A) / P(B1, B2, ..., Bn)
- se utiliza en clasificación de texto, detección de spam, análisis de sentimientos, etc.

#### modelo según distribución de datos
- Gaussiano para datos en forma de camana: si los datos tienen una distribución normal (o gaussiana), ejemplo, medidas de altura, peso..

- Datos de conteno(PNL): si estas trabajando con datos que representan conteos, como la frecuencia de palabras, documentos

- Bernoulli para datos binarios: si los datos son binarios o representan la presencias/ausencia de caracteristicas

In [7]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from wordcloud import WordCloud

# leer datos
df = pd.read_csv(r'C:\Users\ander\Escritorio\PYTHON\Python 2025\Procesamiento_lenguaje_natural_NLP\datasets\spam.csv', encoding='ISO-8859-1')
df = df[['v1', 'v2']]
df.rename(columns = {'v1': 'label', 'v2': 'email'}, inplace = True)
df.head()

  label                                              email
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df['email'][1]

'Ok lar... Joking wif u oni...'

In [11]:
df.tail()

     label                                              email
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [12]:
df.shape

(5572, 2)

In [10]:
# agrupando por label
df_grouped = df.groupby('label').count()
df_grouped

       email
label
ham     4825
spam     747